//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PressAgencySys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class articlePost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articlePost()
        {
            this.DisLikes = new HashSet<DisLike>();
            this.LikesPosts = new HashSet<LikesPost>();
            this.photos = new HashSet<photo>();
        }

        [Display(Name = "Article ID")]
        public int articleID { get; set; }

        [Display(Name = "Editor ID")]
        public Nullable<int> editorID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Article Title")]
        public string articleTitle { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Article Body")]
        public string articlebody { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Post Creation Date")]
        public System.DateTime postCreationDate { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Article Type")]
        public string articleType { get; set; }

        [Display(Name = "Is Accepted")]
        public bool isAccepted { get; set; }

        [Display(Name = "Number Of Viewers")]
        public Nullable<int> NumberOfViewers { get; set; }

        [Display(Name = "Number Of Likes")]
        public Nullable<int> NumberOfLikes { get; set; }

        [Display(Name = "Number Of DisLikes")]
        public Nullable<int> NumberOfDislikes { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisLike> DisLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikesPost> LikesPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<photo> photos { get; set; }
    }
}
