//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PressAgencySys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo
    {
        public int id { get; set; }
        public string title { get; set; }
        public string path { get; set; }
        public Nullable<int> articleid { get; set; }
    
        public virtual articlePost articlePost { get; set; }
    }
}
