//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PressAgencySys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.articlePosts = new HashSet<articlePost>();
            this.DisLikes = new HashSet<DisLike>();
            this.LikesPosts = new HashSet<LikesPost>();
        }

        public int userID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "User Name")]
        public string userName { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Text)]
        public string email { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage = "Confrim Password doesn't match , Try Again")]
        public string confirmPass { get; set; }

        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.PhoneNumber)]
        public int phone { get; set; }

        [Display(Name = "Photo")]
        public string photo { get; set; }


        [Display(Name = "Role ID"), Range(1, 3)]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<int> roleID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articlePost> articlePosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisLike> DisLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikesPost> LikesPosts { get; set; }
        public virtual role role { get; set; }
    }
}
